
---
# handlers file for keycloak

- name: Restart keycloak
  ansible.builtin.systemd:
    name: keycloak
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
