---
# Install and configure vault

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - jq
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

# official doco to get the exact code. https://developer.hashicorp.com/vault/install#linux
- name: Download and install HashiCorp GPG key
  ansible.builtin.shell: |
    wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp APT repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
  args:
    creates: /etc/apt/sources.list.d/hashicorp.list

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Vault
  ansible.builtin.apt:
    name: "vault={{ vault_version }}"
    state: present

- name: Create vault directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0755'
  loop:
    - "{{ vault_data_dir }}"
    - "{{ vault_log_dir }}"

- name: Create Vault configuration file
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'
  notify: restart vault

- name: Create Vault systemd service file
  ansible.builtin.template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart vault

- name: Create Vault environment file
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ vault_config_dir }}/vault.env"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'

- name: Create logrotate configuration for Vault
  ansible.builtin.template:
    src: vault.logrotate.j2
    dest: /etc/logrotate.d/vault
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Vault service
  ansible.builtin.systemd:
    name: vault
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for Vault to be ready
  ansible.builtin.uri:
    url: "http://localhost:{{ vault_port }}/v1/sys/health"
    method: GET
    status_code: [200, 429, 472, 473, 501, 503]
  register: vault_health_check
  until: vault_health_check.status in [200, 429, 472, 473, 501, 503]
  retries: 30
  delay: 5

- include_tasks: initialize.yml
  when: vault_auto_unseal

- include_tasks: keycloak_integration.yml
  when: keycloak_client_secret is defined
