---
# Install and configure vault

---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - jq
      - ca-certificates
      - gnupg
      - lsb-release
    state: present

- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present

- name: Add HashiCorp APT repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp

- name: Update package cache after adding repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install Vault from HashiCorp repository
  ansible.builtin.apt:
    name: vault
    state: present

- name: Create vault directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0755'
  loop:
    - "{{ vault_data_dir }}"
    - "{{ vault_log_dir }}"

- name: Create Vault configuration file
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ vault_config_dir }}/vault.hcl"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'
  notify: restart vault

- name: Create Vault systemd service file
  ansible.builtin.template:
    src: vault.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart vault

- name: Create Vault environment file
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ vault_config_dir }}/vault.env"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: '0640'

- name: Create logrotate configuration for Vault
  ansible.builtin.template:
    src: vault.logrotate.j2
    dest: /etc/logrotate.d/vault
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Vault service
  ansible.builtin.systemd:
    name: vault
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for Vault to be ready
  ansible.builtin.uri:
    url: "http://localhost:{{ vault_port }}/v1/sys/health"
    method: GET
    status_code: [200, 429, 472, 473, 501, 503]
  register: vault_health_check
  until: vault_health_check.status in [200, 429, 472, 473, 501, 503]
  retries: 30
  delay: 5

- include_tasks: initialize.yml
  when: vault_auto_unseal

- include_tasks: keycloak_integration.yml
  when: keycloak_client_secret is defined
