# Static configuration
api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  dnsresolver:
    acme:
      email: jayanath@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: route53
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: INFO
  format: common

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true