# Ansible playbook to configure traefik
---
- name: Deploy and Configure Traefik LXC Container
  hosts: traefik_lxc
  gather_facts: yes
  become: yes

  vars:
    traefik_aws_region: "ap-southeast-2"
    traefik_version: "3.4.0"
    traefik_dynamic_config_files:
      - adguard.yml
      - dashboard.yml
      - pmox.yml
      - middlewares.yml
      - redirect.yml
      - keycloak.yml
      - vault.yml     

  roles:
    - role: traefik
 