
---
# handlers file for traefik

- name: start traefik
  ansible.builtin.systemd:
    name: traefik
    state: started
    enabled: true

- name: restart traefik
  ansible.builtin.systemd:
    name: traefik.service
    state: restarted
    daemon_reload: true    