
---
# handlers file for traefik

- name: restart traefik 
  ansible.builtin.systemd:
    name: traefik.service
    state: restarted

- name: reload traefik 
  ansible.builtin.systemd:
    name: traefik.service
    state: reloaded
