# Ansible playbook to configure traefik
---
- name: Deploy and Configure Vault LXC Container
  hosts: vault_lxc
  gather_facts: yes
  become: yes

  vars_files:
    - secrets.yml

  roles:
    - role: vault
 