---
# tasks file for pg-keycloak role

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install psycopg2 Python library # Required for postgresql
  ansible.builtin.apt:
    name: python3-psycopg2
    state: present

- name: Install PostgreSQL server and client
  ansible.builtin.apt:
    name:
      - "postgresql-{{ postgresql_version }}"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present

- name: Ensure PostgreSQL service is running and enabled
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Create Keycloak database
  community.postgresql.postgresql_db:
    name: "{{ keycloak_db_name }}"
    state: present
    login_user: postgres # default postgres user
  become_user: postgres

- name: Create Keycloak database user
  community.postgresql.postgresql_user:
    name: "{{ keycloak_db_user }}"
    password: "{{ keycloak_db_password }}"
    state: present
  become_user: postgres

- name: Grant all privileges on Keycloak database to Keycloak user
  community.postgresql.postgresql_query:
    login_db: "{{ keycloak_db_name }}"
    query: |
      GRANT ALL PRIVILEGES ON DATABASE {{ keycloak_db_name }} TO {{ keycloak_db_user }};
      GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO {{ keycloak_db_user }};
      GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO {{ keycloak_db_user }};
      GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO {{ keycloak_db_user }};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO {{ keycloak_db_user }};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO {{ keycloak_db_user }};
      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO {{ keycloak_db_user }};
  become_user: postgres

- name: Grant CREATE privilege on public schema to Keycloak user
  community.postgresql.postgresql_query:
    login_db: "{{ keycloak_db_name }}"
    query: "GRANT CREATE ON SCHEMA public TO {{ keycloak_db_user }};"
  become_user: postgres

- name: Configure PostgreSQL to listen on all network interfaces
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'" # Listen on all interfaces (may have to revisit with firewall rules)
    state: present
  notify: Restart postgresql

- name: Configure pg_hba.conf to allow connections from Keycloak LXC
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    insertafter: "^# IPv4 local connections:" # Insert after local connections section to make it neat
    line: "host    {{ keycloak_db_name }}        {{ keycloak_db_user }}    {{ keycloak_container_ip }}/32       md5" # Allow MD5 auth from Keycloak IP
    state: present
  notify: Restart postgresql

